table f_sls_trx

	column CustomerKey
		dataType: int64
		summarizeBy: sum

	column ProductKey
		dataType: int64
		summarizeBy: none
		isHidden

	column OrderDateKey
		dataType: int64
		summarizeBy: none
		isHidden

	column ShipDateKey
		dataType: int64
		summarizeBy: none

	column PromotionKey
		dataType: int64
		summarizeBy: none
		isHidden

	column Amount
		dataType: decimal
		summarizeBy: sum
		isHidden

	column OrderNote
		dataType: string
		summarizeBy: none

	measure 'Total Amount' = SUM(f_sls_trx[Amount])
