/// Sales transactions, one row per order line. Revenue is in local currency.
table Sales

	column CustomerKey
		dataType: int64
		summarizeBy: none
		isHidden

	column ProductKey
		dataType: int64
		summarizeBy: none
		isHidden

	column DateKey
		dataType: int64
		summarizeBy: none
		isHidden

	column GeographyKey
		dataType: int64
		summarizeBy: none
		isHidden

	column Amount
		dataType: decimal
		summarizeBy: sum
		isHidden

	/// Total revenue across all sales, in local currency.
	measure 'Total Revenue' = SUM(Sales[Amount])
